### ISSUE TITLE
 Implement a mechanism to exclude devices used by the platform development team from tracking 

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#155]
**Acceptance Criteria:**
- [ ] A mechanism is implemented that accurately excludes devices used by the platform development team from tracking
- [ ] The mechanism is easy to use and does not interfere with the normal use of the platform
- [ ] The mechanism accurately excludes all necessary devices from tracking
