### ISSUE TITLE
Infopage-Images // As an organization, I want to be able to show more images of my project  so that citizens gain a better understanding

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#70]
**Acceptance Criteria:**

- [ ] Multiple images can be uploaded to a projectroom.
- [ ] Images are displayed in a clear and easy to understand manner

———

**Value for stakeholders:**

Allows for a better understanding of the project for citizens

———

**Helpful information for development team:**

The team should research and implement a feature for uploading and displaying multiple images in a projectroom. 

———

**Possible work streams:**

- [ ] UX: Define the type of images that are needed to be shown
- [ ] UI: Design a solution to show the images of the project
- [ ] Programming: Implement the functionality to show the images of the project

———

**Possible testing strucutre:**

- [ ] Verify that the images of the project are accurate and visible
- [ ] Verify that the images can be viewed in a clear and easy way
